id: IE3D6C24D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T17:37:38+00:00'
last_modified: '2022-06-08T02:41:44.268433+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22950
  title: སོ་སྐྱེས་སྐད་སྒྲ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    4A46:
      image_group_id: I1KG23016
      title: ''
      total_pages: 234
      order: 1
      base_file: 4A46.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
