id: P005383
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22950
  title: སོ་སྐྱེས་སྐད་སྒྲ།
  author: ''
  volumes:
    2464d07fdf7d4ed3b0ac0cf2a7925ba5:
      image_group_id: I1KG23016
      title: ''
      volume_number: 1
      total_pages: 234
